name = "PWFExporter"
uuid = "4e99202f-64fc-48d7-b36a-d4c86e1d4217"
authors = ["Rodrigo Muniz <rodrigosilvamuniz@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
