name = "PWFExporter"
uuid = "4e99202f-64fc-48d7-b36a-d4c86e1d4217"
authors = ["Rodrigo Muniz <rodrigosilvamuniz@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
Format = "1fa38f19-a742-5d3f-a2b9-30dd87b9d5f8"
PWF = "0f4c3beb-4231-4c4d-93e1-709cb40a89e6"

[compat]
Format = "1.3.7"
PWF = "0.0.1"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
